# Description for social sharing and search engines.
description = "Website da disciplina Dados Geoespaciais no R - Unesp (Rio Claro)"

# Default image for social sharing and search engines. Place image in `static/images/` folder and specify image name here.
sharing_image = ""
twitter_image = ""

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ["geor.css"]
custom_js = ["geor.js"]

# Define base hex url for index page (where the stickers link out to)
hex_base_url = ""
hex_ext = ""
    
# Define "news" as both articles and events
mainSections = ["articles", "events"]

# options for highlight.js (version, additional languages, and theme)
disable_highlightjs = "true"
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

[footer]
    github_url = "https://github.com/GeoR-Course/website"
    twitter_url = ""
    support = "Este site foi derivado de [STA 310](https://sta310-sp22.netlify.app/)."

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[authors]
    show_list = "" # on list page, default is true
    show_single = "" # on single pages, default is true
    show_latest = "" # on bio, default is true
    label_latest = "" # on bio, default is "Latest"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[events]
    link_archive = "" # default is true

# customize your site colors
# these colors get applied by layouts/partials/custom-site.css
# then, the layouts/partials/head_includes.html uses that partial
# the partial head_includes.html is called in the partial header.html everywhere!
[colors]
    text = "#404040" # off-black
    # Links
    link = "#2369bd" # main accent
    link_hover = "#2369bd" #lighter
    # Footer
    footer_primary = "#23373b"
    footer_text = "#ffffff" 
    # Backgrounds
    background = "#ffffff" 
    home_section_odd = "#ffffff"
    home_section_even = "#fcfcfc" 
    # Menu
    menu_primary = "#23373b"
    menu_text = "#ffffff"
    menu_text_active = "#2369bd"
    menu_text_current = "#2369bd"
    menu_decorate_current = "none"
    menu_title = "#ffffff" 
    menu_title_active = "#2369bd" 
    menu_box_hover = "#23373b" 
    menu_box_active = "#23373b" 
    
    # Tables
    header_background = "#2369bd"
    table_row_even = "#fcfcfc"
    table_row_odd = "#1a162d10"

